config/routes.rb
MyServiceMod::Application.routes.draw do

  resources :slip_payments

  resources :slip_lines

  resources :receipts

  get "static_pages/home", as: "home"
  root :to => 'static_pages#home'
  
  
  get "print_test", to: "static_pages#print_test", as: "print_test"

  
  namespace :newer do 
    get "services/summary", to: "services#summary"
    resources :services
  end
  
  namespace :newer do 
    get "services2/summary", to: "aaa::services2#summary"
    resources :services2
  end
  
  resources :branches
  resources :trades
  resources :services
  resources :users 
  

end

app/controllers/static_pages_controller.rb
#encoding: utf-8
class StaticPagesController < ApplicationController
   helper_method :all

  def home
  end
  
  def print_test
    @time = Time.current
    respond_to do |format|
      format.html # show.html.erb
      format.json do render json: if params[:roundRobin]
                                    testRoundRobin
                                  else
                                      testSlip
                                  end
      end
    end
  end
  
  def initialize
    super
      @test_slips = {oneCentSlip: %q{{"cashbox" : "XX99",
                                      "cashierName" : "Rafał ąćęłńóśźż",
                                      "created" : 1377262368237,
                                      "errorNote" : "Nowy",
                                      "printingState" : "Created",
                                      "reference" : "R-k 0123456789",
                                      "slipLines" : [
                                          { "amount" : 1,
                                            "discount" : 0,
                                            "discountType" : "NoDiscount",
                                            "name" : "Test drukarki",
                                            "price" : 0.01,
                                            "taxRate" : "VAT23"
                                          } ],
                                      "slipPayments" : [ { "amount" : 0.01,
                                            "type" : "Cash"
                                          } ]
                                    }
                    },

                    noDiscountSlip: %q{{"cashbox" : "XX99",
                                        "cashierName" : "Rafał ąćęłńóśźż",
                                        "created" : 1377265000914,
                                        "errorNote" : "Nowy",
                                        "printingState" : "Created",
                                        "reference" : "R-k 0123456789",
                                        "slipLines" : [ { "amount" : 1,
                                              "discount" : 0,
                                              "discountType" : "NoDiscount",
                                              "name" : "Test drukarki",
                                              "price" : 0.01,
                                              "taxRate" : "VAT23"
                                            } ],
                                        "slipPayments" : [ { "amount" : 0.01,
                                              "type" : "Cash"
                                            } ]
                                       }
                    }
    } 
  end
  
  def testSlip
    slip = params[:slip]
    if slip.respond_to? :to_sym
      slip = slip.to_sym
    else
      return "{}"
    end
    slip_json = @test_slips[slip]
    slip_json ? slip_json : "{}"
  end

  def testRoundRobin
    Rails.logger.debug session.inspect
    call_count = session[:testRoundRobin_call_count] || 0
    if call_count % 2 == 0
      call_count += 1
      session[:testRoundRobin_call_count] = call_count
      @test_slips[:oneCentSlip]
    else
      call_count += 1
      session[:testRoundRobin_call_count] = call_count
      @test_slips[:noDiscountSlip]
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
%h1 StaticPages#home
%p Find me in app/views/static_pages/home.html.haml

%header
%nav
  %ul
    %li= link_to "Usługi - lista (TODO)"
    %li= link_to "Historia usługi (TODO)"
    %li= link_to "Karta usługi (TODO)"
    %li= link_to "Statystyki usługi (TODO)"
    %li= link_to "Dodawanie usługi (TODO)"
    %li= link_to "first print test in RoR", print_test_path

%ul
  %li= link_to "urzytkownicy", users_path
  %li= link_to "usługi", services_path
  %li= link_to "branże", trades_path
  %li= link_to "salony", branches_path

app/views/static_pages/print_test.html.haml
%p strona załadowana #{@time}

%div 
  Hello fiscal printer :-)
  %p 
  = form_tag("#", {method: "get", remote: "true", onsubmit:"versumPrinter.savePrinterConfiguration(driver.value, port.value); return false;"}) do 
    = select_tag "driver", options_for_select({ "DFEmul"          => "DFEmul",
                                                "Java console"    => :BogusFiscalPrinter,
                                                "ElzabMera"       => "ElzabMera", 
                                                "ElzabOmega2"     => "ElzabOmega2", 
                                                "InnovaProfit451" => "InnovaProfit451", 
                                                "OptimusVivo"     => "OptimusVivo", 
                                                "Posnet101"       => "Posnet101", 
                                                "Thermal101"      => "Thermal101",
                                                "Thermal203"      => "Thermal203", 
                                                "Thermal301"      => "Thermal301", 
                                                "ThermalOld"      => "ThermalOld"}, 
                                              :BogusFiscalPrinter)
    .field 
      = label_tag :port, "Serial port"
      = text_field_tag :port, "COM5"
    = submit_tag "Save configuration"
  %hr
  
= form_tag("#", {method: "get", remote: "true", onsubmit: "versumPrinter.testApplet('hello world'); return false;"}) do
  = submit_tag "test access to applet"
  

.print_server_applet     
  :erb
    <applet id="PrintingServerApplet"
        name="fpsApplet"
        code="name.prokop.bart.fps.applet.FiscalPrinterOblokApplet.class"
        width=400
        height=400
      archive="java/fps-1.0-SNAPSHOT-applet.jar">

      <param name="cache_option" value="no"/>
      <param name="persistState" value="false" />

      <param name="SerialPort" value="/dev/ttyS105">
      <param name="FiscalPrinterType" value="BogusFiscalPrinter">
      <param name="permissions" value="all-permissions"></param>
    </applet>

%hr
Test of access to json for printing (see responses from server in browser's developer tools)
= form_tag("print_test.json", {method: "get", remote: "true"}) do
  = select_tag "slip", options_for_select({ "one Cent Slip"       => "oneCentSlip",
                                            "No Discount Slip"    => "noDiscountSlip",
                                            "empty"                => "Slip"},
                                            :"oneCentSlip.json")
  = submit_tag "get json"


%hr //TODO: somday, maybe, (if needed in testing)
= form_tag("print_test.json", {method: "get", remote: "true"}) do
  = select_tag "slip", options_for_select({ "one Cent Slip"       => "oneCentSlip",
                                            "No Discount Slip"    => "noDiscountSlip",
                                            "Slip"                => "Slip"},
                                            :"oneCentSlip.json")
  = submit_tag "print"


%hr
#see-status SSE status: <br>

#printing-status  Printing status: <br>

%hr
js test, start/stop pooling
= submit_tag "start pooling", :type => 'button', :onclick => 'versumPrinter.startListeningForSlipsToPrint("http://oblok.test.pl:4000/print_test.json", {roundRobin: true} );'
= submit_tag "stop pooling", :type => 'button', :onclick => 'versumPrinter.stopListeningForSlipsToPrint();'

%hr
#jsonoutput
  use this to get sample Slips array a json: 
  = submit_tag "get test slips as jason", :type => 'button', :onclick => 'versumPrinter.getTestSlipsAsJson();'
  %ul



= javascript_include_tag "printing"