config/routes.rb
MyServiceMod::Application.routes.draw do

  resources :slip_payments

  resources :slip_lines

  resources :receipts

  get "static_pages/home", as: "home"
  root :to => 'static_pages#home'
  
  
  get "print_test", to: "static_pages#print_test", as: "print_test"

  
  namespace :newer do 
    get "services/summary", to: "services#summary"
    resources :services
  end
  
  namespace :newer do 
    get "services2/summary", to: "aaa::services2#summary"
    resources :services2
  end
  
  resources :branches
  resources :trades
  resources :services
  resources :users 
  

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.haml
= form_for @branch do |f|
  - if @branch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@branch.errors.count, "error")} prohibited this branch from being saved:"
      %ul
        - @branch.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label      'Podaj nazwę'
    = f.text_field :name

  .field
    = f.label      :descrioption, "Opis"
    = f.text_field :description

  .actions
    = f.submit 'Save'

app/views/branches/edit.html.haml
%h1 Editing branch

= render 'form'

= link_to 'Show', @branch
\|
= link_to 'Back', branches_path

app/views/branches/index.html.haml
%h1 Listing branches

%table
  %tr
    %th Name
    %th Descr...
    %th
    %th
    %th

  - @branches.each do |branch|
    %tr
      %td= branch.name
      %td= branch.description
      %td= link_to 'Show', branch
      %td= link_to 'Edit', edit_branch_path(branch)
      %td= link_to 'Destroy', branch, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Branch', new_branch_path

app/views/branches/new.html.haml
%h1 New branch

= render 'form'

= link_to 'Back', branches_path

app/views/branches/show.html.haml
%p#notice= notice

%p 
  %b Ten branch ma nazwę:
  = @branch.name

%p
  %b Ten branch ma opis:
  = @branch.description
    
%p 
  %b i oczywiście id:
  = @branch.id


= link_to 'Edit', edit_branch_path(@branch)
\|
= link_to 'Back', branches_path

= link_to 'Strona startowa', static_pages_home_path