config/routes.rb
MyServiceMod::Application.routes.draw do

  resources :slip_payments

  resources :slip_lines

  resources :receipts

  get "static_pages/home", as: "home"
  root :to => 'static_pages#home'
  
  
  get "print_test", to: "static_pages#print_test", as: "print_test"

  
  namespace :newer do 
    get "services/summary", to: "services#summary"
    resources :services
  end
  
  namespace :newer do 
    get "services2/summary", to: "aaa::services2#summary"
    resources :services2
  end
  
  resources :branches
  resources :trades
  resources :services
  resources :users 
  

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :branch_id, :description, :duration, :name, :price, :trade_id
end

app/controllers/newer/services2_controller.rb
class Newer::Services2Controller < ApplicationController
  
  #TODO
  def summary
  end

  #TODO
  def history
  end

  #TODO
  def statistics
  end
  
  #TODO
  def show
    @service = Service.find params[:id]
  end
end

app/controllers/newer/services_controller.rb
class Newer::ServicesController < ApplicationController
  def summary
  end

  def history
  end

  def statistics
  end
  
  
  def show
    @service = Service.find params[:id]
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @time = Date.current
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/newer/services2_helper.rb
module Newer::Services2Helper
end

app/helpers/newer/services_helper.rb
module Newer::ServicesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/newer/services/history.html.haml
%h1 New::Services#history
%p Find me in app/views/new/services/history.html.haml

app/views/newer/services/index.html.haml
%h1 Listing services

%table
  %tr
    %th Branch
    %th Description
    %th Duration
    %th Name
    %th Price
    %th Trade
    %th
    %th
    %th

  - @services.each do |service|
    %tr
      %td= service.branch_id
      %td= service.description
      %td= service.duration
      %td= service.name
      %td= service.price
      %td= service.trade_id
      %td= link_to 'Show', service
      %td= link_to 'Edit', edit_service_path(service)
      %td= link_to 'Destroy', service, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
%b mamy dzisiaj: #{@time}
%br
= link_to 'New Service', new_service_path

app/views/newer/services/show.html.haml
%p#notice= notice

%h1 newer show
%p
  %b Branch:
  = @service.branch_id
%p
  %b Description:
  = @service.description
%p
  %b Duration:
  = @service.duration
%p
  %b Name:
  = @service.name
%p
  %b Price:
  = @service.price
%p
  %b Trade:
  = @service.trade_id

= link_to 'Edit', edit_service_path(@service)
\|
= link_to 'Back', services_path

app/views/newer/services/statistics.html.haml
%h1 New::Services#statistics
%p Find me in app/views/new/services/statistics.html.haml

app/views/newer/services/summary.html.haml
%h1 New::Services#summary
%p Find me in app/views/new/services/summary.html.haml