config/routes.rb
MyServiceMod::Application.routes.draw do

  resources :slip_payments

  resources :slip_lines

  resources :receipts

  get "static_pages/home", as: "home"
  root :to => 'static_pages#home'
  
  
  get "print_test", to: "static_pages#print_test", as: "print_test"

  
  namespace :newer do 
    get "services/summary", to: "services#summary"
    resources :services
  end
  
  namespace :newer do 
    get "services2/summary", to: "aaa::services2#summary"
    resources :services2
  end
  
  resources :branches
  resources :trades
  resources :services
  resources :users 
  

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  attr_accessible :branch_id, :cashbox, :cashier_name, :error_note, :printing_state, :reference
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.haml
= form_for @receipt do |f|
  - if @receipt.errors.any?
    #error_explanation
      %h2= "#{pluralize(@receipt.errors.count, "error")} prohibited this receipt from being saved:"
      %ul
        - @receipt.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :cashbox
    = f.text_field :cashbox
  .field
    = f.label :cashier_name
    = f.text_field :cashier_name
  .field
    = f.label :error_note
    = f.text_field :error_note
  .field
    = f.label :printing_state
    = f.text_field :printing_state
  .field
    = f.label :reference
    = f.text_field :reference
  .field
    = f.label :branch_id
    = f.number_field :branch_id
  .actions
    = f.submit 'Save'

app/views/receipts/edit.html.haml
%h1 Editing receipt

= render 'form'

= link_to 'Show', @receipt
\|
= link_to 'Back', receipts_path

app/views/receipts/index.html.haml
%h1 Listing receipts

%table
  %tr
    %th Cashbox
    %th Cashier name
    %th Error note
    %th Printing state
    %th Reference
    %th Branch
    %th
    %th
    %th

  - @receipts.each do |receipt|
    %tr
      %td= receipt.cashbox
      %td= receipt.cashier_name
      %td= receipt.error_note
      %td= receipt.printing_state
      %td= receipt.reference
      %td= receipt.branch_id
      %td= link_to 'Show', receipt
      %td= link_to 'Edit', edit_receipt_path(receipt)
      %td= link_to 'Destroy', receipt, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Receipt', new_receipt_path

app/views/receipts/new.html.haml
%h1 New receipt

= render 'form'

= link_to 'Back', receipts_path

app/views/receipts/show.html.haml
%p#notice= notice

%p
  %b Cashbox:
  = @receipt.cashbox
%p
  %b Cashier name:
  = @receipt.cashier_name
%p
  %b Error note:
  = @receipt.error_note
%p
  %b Printing state:
  = @receipt.printing_state
%p
  %b Reference:
  = @receipt.reference
%p
  %b Branch:
  = @receipt.branch_id

= link_to 'Edit', edit_receipt_path(@receipt)
\|
= link_to 'Back', receipts_path